"""Portal configurations for code violation scraping.

Each portal defines: API URL, type (socrata/arcgis), field mappings,
and filter criteria for pulling open violations from the last 30 days.
"""

from __future__ import annotations

VIOLATION_KEYWORDS = [
    # Structural / safety — indicates seriously distressed property
    "condemn", "dilapidat", "deteriorat", "unsafe", "hazard",
    "blight", "nuisance", "abandon", "vacant", "board",
    "uninhabit", "unfit", "substandard", "insanit",
    # Structural damage
    "structur", "collaps", "foundation", "roof damage", "fire damage",
    # Severe neglect
    "overgrown", "debris", "junk", "trash", "rubbish",
    "deferred", "unmaintain", "accumul",
]

PORTALS: list[dict] = [
    {
        "id": "cincinnati_oh",
        "name": "Cincinnati, OH",
        "state": "OH",
        "county": "Hamilton",
        "type": "socrata",
        "base_url": "https://data.cincinnati-oh.gov",
        "dataset_id": "cncm-znd6",
        "field_map": {
            "address": "full_address",
            "violation_type": "comp_type_desc",
            "violation_subtype": "sub_type_desc",
            "status": "data_status_display",
            "date_opened": "entered_date",
            "latitude": "latitude",
            "longitude": "longitude",
        },
        "status_filter": "data_status_display NOT IN ('CLOSED','CANCEL')",
        "date_field": "entered_date",
    },
    {
        "id": "austin_tx",
        "name": "Austin, TX",
        "state": "TX",
        "county": "Travis",
        "type": "socrata",
        "base_url": "https://data.austintexas.gov",
        "dataset_id": "6wtj-zbtb",
        "field_map": {
            "address": "address",
            "violation_type": "description",
            "status": "status",
            "date_opened": "opened_date",
            "date_closed": "closed_date",
            "case_id": "case_id",
            "zip": "zip_code",
            "latitude": "latitude",
            "longitude": "longitude",
            "parcel": "parcelid",
        },
        "status_filter": "status = 'Active'",
        "date_field": "opened_date",
    },
    {
        "id": "cleveland_oh",
        "name": "Cleveland, OH",
        "state": "OH",
        "county": "Cuyahoga",
        "type": "arcgis",
        "base_url": "https://services3.arcgis.com/dty2kHktVXHrqO8i/arcgis/rest/services/Violation_Status_History/FeatureServer/0",
        "field_map": {
            "address": "PRIMARY_ADDRESS",
            "violation_type": "TYPE_OF_VIOLATION",
            "status": "TASK_STATUS",
            "task": "TASK_NAME",
            "date_opened": "FILE_DATE",
            "parcel": "PARCEL_NUMBER",
            "case_id": "RECORD_ID",
        },
        "where_filter": "TASK_STATUS NOT IN ('Completed','Closed','Void')",
        "date_field": "FILE_DATE",
    },
    {
        "id": "fort_worth_tx",
        "name": "Fort Worth, TX",
        "state": "TX",
        "county": "Tarrant",
        "type": "arcgis",
        "base_url": "https://services5.arcgis.com/3ddLCBXe1bRt7mzj/arcgis/rest/services/CFW_Open_Data_Code_Violations_Table_view/FeatureServer/0",
        "field_map": {
            "address": "Violation_Address",
            "city": "City",
            "state_field": "State",
            "violation_type": "Complaint_Type_Description",
            "status": "Violation_Current_Status",
            "case_status": "Case_Current_Status",
            "date_opened": "Case_Created_Date",
            "case_id": "Case_ID",
            "latitude": "Latitude",
            "longitude": "Longitude",
        },
        "where_filter": "Violation_Current_Status <> 'Closed'",
        "date_field": "Case_Created_Date",
    },
    {
        "id": "kansas_city_mo",
        "name": "Kansas City, MO",
        "state": "MO",
        "county": "Jackson",
        "type": "socrata",
        "base_url": "https://data.kcmo.org",
        "dataset_id": "vq3e-m9ge",
        "field_map": {
            "address": "full_address",
            "violation_type": "description",
            "violation_subtype": "ord_text",
            "status": "vio_status",
            "date_opened": "date_found",
            "case_id": "casenumber",
            "zip": "postalcode",
        },
        "status_filter": "vio_status != 'In Compliance'",
        "date_field": "date_found",
    },
    {
        "id": "philadelphia_pa",
        "name": "Philadelphia, PA",
        "state": "PA",
        "county": "Philadelphia",
        "type": "carto",
        "base_url": "https://phl.carto.com/api/v2/sql",
        "table_name": "violations",
        "field_map": {
            "address": "address",
            "violation_type": "violationcode",
            "violation_subtype": "violationcodetitle",
            "status": "violationstatus",
            "date_opened": "violationdate",
            "case_id": "casenumber",
            "zip": "zip",
        },
        "extra_where": "violationstatus = 'OPEN'",
        "date_field": "violationdate",
    },
    {
        "id": "detroit_mi",
        "name": "Detroit, MI",
        "state": "MI",
        "county": "Wayne",
        "type": "arcgis",
        "base_url": "https://services2.arcgis.com/qvkbeam7Wirps6zC/ArcGIS/rest/services/blight_tickets/FeatureServer/0",
        "field_map": {
            "address": "address",
            "violation_type": "ordinance_description",
            "status": "judgment_status",
            "date_opened": "ticket_issued_date",
            "case_id": "ticket_number",
            "zip": "zip_code",
            "city": "city",
            "state_field": "state",
        },
        "where_filter": "1=1",
        "date_field": "ticket_issued_date",
    },
    {
        "id": "chicago_il",
        "name": "Chicago, IL",
        "state": "IL",
        "county": "Cook",
        "type": "socrata",
        "base_url": "https://data.cityofchicago.org",
        "dataset_id": "22u3-xenr",
        "field_map": {
            "address": "address",
            "violation_type": "violation_description",
            "violation_subtype": "violation_ordinance",
            "status": "violation_status",
            "date_opened": "violation_date",
            "case_id": "inspection_number",
            "latitude": "latitude",
            "longitude": "longitude",
        },
        "status_filter": "violation_status = 'OPEN'",
        "date_field": "violation_date",
    },
    {
        "id": "baltimore_md",
        "name": "Baltimore, MD",
        "state": "MD",
        "county": "Baltimore City",
        "type": "arcgis",
        "base_url": "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/1",
        "field_map": {
            "address": "Address",
            "violation_type": "NT",
            "date_opened": "DateNotice",
            "case_id": "NoticeNum",
            "parcel": "BLOCKLOT",
        },
        "where_filter": "DateCancel IS NULL",
        "date_field": "DateNotice",
    },
    {
        "id": "buffalo_ny",
        "name": "Buffalo, NY",
        "state": "NY",
        "county": "Erie",
        "type": "socrata",
        "base_url": "https://data.buffalony.gov",
        "dataset_id": "ivrf-k9vm",
        "field_map": {
            "address": "address",
            "violation_type": "description",
            "violation_subtype": "code",
            "status": "status",
            "date_opened": "date",
            "case_id": "case_number",
            "zip": "zip",
            "latitude": "latitude",
            "longitude": "longitude",
        },
        "status_filter": "status NOT IN ('COMPLIED','CLOSED')",
        "date_field": "date",
    },
    {
        "id": "louisville_ky",
        "name": "Louisville, KY",
        "state": "KY",
        "county": "Jefferson",
        "type": "arcgis",
        "base_url": "https://services1.arcgis.com/79kfd2K6fskCAkyg/arcgis/rest/services/pm_open_workorders/FeatureServer/0",
        "field_map": {
            "address_number": "HOUSE_NUMBER",
            "street_name": "STREET_NAME",
            "street_suffix": "STREET_SUFFIX",
            "violation_type": "RECORD_TYPE",
            "violation_subtype": "WORK_DESCRIPTION",
            "status": "RECORD_STATUS",
            "date_opened": "DATE_OPENED",
            "case_id": "RECORD_ID",
            "zip": "ZIPCODE",
            "latitude": "LATITUDE",
            "longitude": "LONGITUDE",
        },
        "where_filter": "1=1",
        "date_field": "DATE_OPENED",
    },
    {
        "id": "miami_dade_fl",
        "name": "Miami-Dade County, FL",
        "state": "FL",
        "county": "Miami-Dade",
        "type": "arcgis",
        "base_url": "https://services.arcgis.com/8Pc9XBTAsYuxx9Ny/arcgis/rest/services/CodeComplianceViolation_Open_View/FeatureServer/0",
        "field_map": {
            "address": "ADDRESS",
            "violation_type": "PROBLEM_DESC",
            "status": "STAT_DESC",
            "date_opened": "CASE_DATE",
            "case_id": "CASE_NUM",
            "parcel": "FOLIO",
        },
        "where_filter": "1=1",
        "date_field": "CASE_DATE",
    },
]
